1.31.151.siab_Production_Build

diff --git a/swampinabox/runtime/bin/install_platform b/swampinabox/runtime/bin/install_platform
--- a/swampinabox/runtime/bin/install_platform
+++ b/swampinabox/runtime/bin/install_platform
@@ -9,16 +9,17 @@
 # Install a VM disk image as a new platform for assessments.
 #
 
-mysql_cnf_file="/opt/swamp/sql/sql.cnf"
-mysql_passwd_file="/etc/.mysql_root"
-platforms_image_dest="/swamp/platforms/images"
-platforms_script_root="/opt/swamp/sql"
+##########################################################################
 
+platforms_image_store="/swamp/platforms/images"
+platforms_script_store="/opt/swamp/sql/platforms"
 vm_image_src="$1"
-vm_image_dest="$platforms_image_dest/$(basename "$vm_image_src")"
-platform=$(basename "$vm_image_src")
-platform="${platform//condor-/}"
-platform="${platform//-master*/}"
+vm_image_dest="$platforms_image_store/$(basename "$vm_image_src")"
+
+##########################################################################
+
+mysql_passwd_file="/etc/.mysql_root"
+mysql_cnf_file="/opt/swamp/sql/sql.cnf"
 
 function do_clean_up {
     stty echo
@@ -33,7 +34,7 @@ function exit_normally {
 
 function exit_with_error {
     do_clean_up
-    echo "$0: Error while attempting to install $vm_image_src"
+    echo "$0: Error while attempting to install: $vm_image_src" 1>&2
     exit 1
 }
 
@@ -45,96 +46,107 @@ trap 'exit_with_error' INT TERM
 ##########################################################################
 
 ask_pass() {
-    PROMPT=$1
-    if [ "$2" = "-confirm" ]; then NEED_CONFIRM=1; else NEED_CONFIRM=0; fi
-    NEED_PASSWORD=1
+    prompt="$1"
+    if [ "$2" = "-confirm" ]; then need_confirm=1; else need_confirm=0; fi
+    need_password=1
 
-    while [ "$NEED_PASSWORD" -eq 1 ]; do
+    while [ "$need_password" -eq 1 ]; do
         ANSWER=""
         CONFIRMATION=""
 
-        read -r -e -s -p "$PROMPT " ANSWER
+        read -r -s -p "$prompt " ANSWER
         echo
 
         if [ -z "$ANSWER" ]; then
             echo "*** Password cannot be empty. ***"
         else
-            if [ "$NEED_CONFIRM" -eq 1 ]; then
-                stty -echo
-                echo -n "Retype password: "
-                read -r CONFIRMATION
+            if [ "$need_confirm" -eq 1 ]; then
+                read -r -s -p "Retype password: " CONFIRMATION
                 echo
-                stty echo
 
                 if [ "$ANSWER" != "$CONFIRMATION" ]; then
                     echo "*** Passwords do not match. ***"
                 else
-                    NEED_PASSWORD=0
+                    need_password=0
                 fi
             else
-                NEED_PASSWORD=0
+                need_password=0
             fi
         fi
     done
 }
 
-function test_db_password {
-    username="$1"
+function save_password_to_disk() {
+    destination="$1"
     password="$2"
 
-    #
-    # In the options file for MySQL:
-    #   - Quote the password, in case it contains '#'.
-    #   - Escape backslashes (the only character that needs escaping).
-    #
-    # See: http://dev.mysql.com/doc/refman/5.7/en/option-files.html
-    #
-    password=${password//\\/\\\\}
+    reset_umask="$(umask -p)"
+    umask 377
 
-    echo '[client]' > "$mysql_cnf_file"
-    chmod 400 "$mysql_cnf_file"
-    echo "password='$password'" >> "$mysql_cnf_file"
-    echo "user='$username'" >> "$mysql_cnf_file"
+    rm -f "$destination"
+    echo "$password" | sudo openssl enc -aes-256-cbc -salt -out "$destination" -pass pass:swamp
+    chmod 400 "$destination"
 
-    mysql --defaults-file="$mysql_cnf_file" <<< ';'
-    success=$?
+    $reset_umask
+}
 
-    rm -f "$mysql_cnf_file"
+function test_db_password() {
+    username="$1"
+    password="$2"
+    encountered_error=0
 
-    if [ $success -ne 0 ]; then
-        echo "Error: Failed to log into the database as $username"
-        return 1
+    save_password_to_disk "$mysql_passwd_file" "$password"
+    /opt/swamp/sbin/create_mysql_root_cnf "$mysql_cnf_file" "$mysql_passwd_file" "$username"
+
+    if ! mysql --defaults-file="$mysql_cnf_file" <<< ';' ; then
+        echo "Error: Failed to log into the database as '$username'" 1>&2
+        encountered_error=1
     fi
 
-    return 0
+    do_clean_up
+    return $encountered_error
 }
 
 ##########################################################################
 
 if [ -z "$vm_image_src" ]; then
-    echo "Usage: $0 <VM platform .qcow2 or .qcow2.gz file>"
+    echo "Usage: $0 <VM platform .qcow2 or .qcow2.gz file>" 1>&2
     exit 1
 fi
 
 if [ ! -r "$vm_image_src" ]; then
-    echo "Error: $vm_image_src is not readable"
+    echo "Error: File does not exist or is not readable: $vm_image_src" 1>&2
     exit 1
 fi
 
-if [[ !("$vm_image_src" =~ .qcow2$) && !("$vm_image_src" =~ .qcow2.gz$) ]]; then
-    echo "Error: $vm_image_src does not look like a .qcow2 or .qcow.gz file"
+if [[ ! ( "$vm_image_src" =~ .qcow2$ ) && ! ( "$vm_image_src" =~ .qcow2.gz$ ) ]]; then
+    echo "Error: Not a '.qcow2' or 'qcow2.gz' file: $vm_image_src" 1>&2
     exit 1
 fi
 
-echo "$(basename "$vm_image_src") looks like the following platform: $platform"
+platform_install_sql=""
+for platform_sql in "$platforms_script_store"/*.sql ; do
+    platform=$(basename "$platform_sql" .sql)
+    platform=${platform/\.minorversion/}
 
-if [ ! -e "$platforms_script_root/$platform.sql" ]; then
-    echo "Error: $platform is not recognized as an installable platform"
+    if [[ $platform =~ (.*)(-32|-64) ]]; then
+        distribution=${BASH_REMATCH[1]}
+        bits=${BASH_REMATCH[2]}
+
+        if [[ $(basename "$vm_image_src") =~ ^"condor-$distribution".*"$bits-master".*".qcow2" ]]; then
+            platform_install_sql="$platform_sql"
+            break
+        fi
+    fi
+done
+
+if [ -z "$platform_install_sql" ]; then
+    echo "Error: Not a recognized installable platform: $vm_image_src" 1>&2
     exit 1
 fi
 
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: The install must be performed as root."
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
@@ -143,7 +155,7 @@ fi
 success=1
 while [ $success -ne 0 ]; do
     ask_pass "Enter database root password:"
-    DBROOT=$ANSWER
+    DBROOT="$ANSWER"
 
     test_db_password root "$DBROOT"
     success=$?
@@ -152,10 +164,7 @@ done
 ##########################################################################
 
 if [[ "$vm_image_src" =~ .qcow2$ ]]; then
-    echo "Copying $(basename "$vm_image_src") to $platforms_image_dest"
-
-    # echo src: "$vm_image_src"
-    # echo dest: "$vm_image_dest"
+    echo "Copying '$(basename "$vm_image_src")' to '$platforms_image_store'"
 
     cp    "$vm_image_src" "$vm_image_dest" || exit_with_error
     chown root:root       "$vm_image_dest" || exit_with_error
@@ -163,12 +172,9 @@ if [[ "$vm_image_src" =~ .qcow2$ ]]; then
 fi
 
 if [[ "$vm_image_src" =~ .gz$ ]]; then
-    echo "Unzipping $(basename "$vm_image_src") into $platforms_image_dest"
+    echo "Unzipping '$(basename "$vm_image_src")' into '$platforms_image_store'"
 
     vm_image_dest=${vm_image_dest%%.gz}
-
-    # echo src: "$vm_image_src"
-    # echo dest: "$vm_image_dest"
 
     gunzip -c "$vm_image_src" > "$vm_image_dest" || exit_with_error
     chown root:root  "$vm_image_dest" || exit_with_error
@@ -179,14 +185,10 @@ fi
 
 echo "Updating database records"
 
-echo "$DBROOT" | sudo openssl enc -aes-256-cbc -salt -out "$mysql_passwd_file" -pass pass:swamp
-chmod 400 "$mysql_passwd_file"
-/opt/swamp/sbin/execute_sql_script "$platforms_script_root/$platform.sql" || exit_with_error
-rm -f "$mysql_passwd_file"
+save_password_to_disk "$mysql_passwd_file" "$DBROOT"       || exit_with_error
+/opt/swamp/sbin/execute_sql_script "$platform_install_sql" || exit_with_error
 
 ##########################################################################
 
-echo ""
-echo "$platform should now be available for performing assessments"
-
+echo "Install completed normally"
 exit_normally
diff --git a/swampinabox/runtime/bin/swamp_set_db_host b/swampinabox/runtime/bin/swamp_set_db_host
--- a/swampinabox/runtime/bin/swamp_set_db_host
+++ b/swampinabox/runtime/bin/swamp_set_db_host
@@ -9,26 +9,28 @@
 # Set the hostname of the database in all relevant configuration locations.
 #
 
+encountered_error=0
+trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+set -o errtrace
+
+############################################################################
+
 NEW_HOSTNAME="$1"
 
 if [ -z "$NEW_HOSTNAME" ]; then
-    echo "Usage: $0 <new hostname>"
+    echo "Usage: $0 <new hostname>" 1>&2
     exit 1
 fi
 
-IP_ADDRESS=$(perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 2>/dev/null)
-
-if [ $? -ne 0 ]; then
-    echo "Error: Unable to determine an IP address for $NEW_HOSTNAME."
+if ! perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 1>/dev/null 2>/dev/null ; then
+    echo "Error: Unable to determine an IP address for: $NEW_HOSTNAME" 1>&2
     exit 1
 fi
 
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: This utility must be run as root. Perhaps use 'sudo'."
+    echo "Error: This utility must be run as root. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
-
-echo "Beginning to configure $NEW_HOSTNAME as the database host"
 
 #
 # Simple function for abstracting out the invocation of 'sed'.
@@ -42,7 +44,7 @@ function update_config() {
     val=${val//\//\\\/}
 
     if [ -r "$target" ]; then
-        echo "Updating $target ($key)"
+        echo "Updating: $target: $key"
         if [ "$nospace" = "-nospace" ]; then
             sed -i "s/^\s*$key\s*=.*$/$key=$val/" "$target"
         else
@@ -56,7 +58,7 @@ function update_config() {
 #
 target="/opt/swamp/etc/swamp.conf"
 
-update_config "dbQuartermasterURL" "jdbc:mariadb://$NEW_HOSTNAME:3306/" "$target"
+update_config "dbPerlDsnHost" "$NEW_HOSTNAME" "$target"
 
 #
 # Update .env (web server)
@@ -67,4 +69,4 @@ for key in ASSESSMENT_DB_HOST PACKAGE_DB_HOST PLATFORM_DB_HOST PROJECT_DB_HOST T
     update_config "$key" "$NEW_HOSTNAME" "$target" -nospace
 done
 
-echo "Finished configuring $NEW_HOSTNAME as the database host"
+exit $encountered_error
diff --git a/swampinabox/runtime/bin/swamp_set_htcondor_host b/swampinabox/runtime/bin/swamp_set_htcondor_host
--- a/swampinabox/runtime/bin/swamp_set_htcondor_host
+++ b/swampinabox/runtime/bin/swamp_set_htcondor_host
@@ -7,30 +7,32 @@
 
 #
 # Set the hostname of the HTCondor installation in all relevant
-# configuration locations.  There's an implicit assumption here that the
+# configuration locations. There's an implicit assumption here that the
 # entire installation is running on one host.
 #
+
+encountered_error=0
+trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+set -o errtrace
+
+############################################################################
 
 NEW_HOSTNAME="$1"
 
 if [ -z "$NEW_HOSTNAME" ]; then
-    echo "Usage: $0 <new hostname>"
+    echo "Usage: $0 <new hostname>" 1>&2
     exit 1
 fi
 
-IP_ADDRESS=$(perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 2>/dev/null)
-
-if [ $? -ne 0 ]; then
-    echo "Error: Unable to determine an IP address for $NEW_HOSTNAME."
+if ! IP_ADDRESS=$(perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 2>/dev/null) ; then
+    echo "Error: Unable to determine an IP address for: $NEW_HOSTNAME" 1>&2
     exit 1
 fi
 
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: This utility must be run as root. Perhaps use 'sudo'."
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
-
-echo "Beginning to configure $NEW_HOSTNAME as the HTCondor host"
 
 #
 # Simple function for abstracting out the invocation of 'sed'.
@@ -44,7 +46,7 @@ function update_config() {
     val=${val//\//\\\/}
 
     if [ -r "$target" ]; then
-        echo "Updating $target ($key)"
+        echo "Updating: $target: $key"
         if [ "$nospace" = "-nospace" ]; then
             sed -i "s/^\s*$key\s*=.*$/$key=$val/" "$target"
         else
@@ -58,18 +60,14 @@ function update_config() {
 #
 target="/opt/swamp/etc/swamp.conf"
 
-for key in htcondor_collector_host; do
-    update_config "$key" "$NEW_HOSTNAME" "$target"
-done
+update_config "htcondor_collector_host" "$NEW_HOSTNAME" "$target"
 
 #
 # Update .env (web server)
 #
 target="/var/www/swamp-web-server/.env"
 
-for key in HTCONDOR_COLLECTOR_HOST; do
-    update_config "$key" "$NEW_HOSTNAME" "$target" -nospace
-done
+update_config "HTCONDOR_COLLECTOR_HOST" "$NEW_HOSTNAME" "$target" -nospace
 
 #
 # Update /etc/condor/config.d (HTCondor itself)
@@ -87,4 +85,4 @@ if [ "$htcondor_service_status" = "running" ]; then
     /opt/swamp/sbin/swamp_manage_service condor restart
 fi
 
-echo "Finished configuring $NEW_HOSTNAME as the HTCondor host"
+exit $encountered_error
diff --git a/swampinabox/runtime/bin/swamp_set_web_host b/swampinabox/runtime/bin/swamp_set_web_host
--- a/swampinabox/runtime/bin/swamp_set_web_host
+++ b/swampinabox/runtime/bin/swamp_set_web_host
@@ -9,26 +9,28 @@
 # Set the hostname of the web server in all relevant configuration locations.
 #
 
+encountered_error=0
+trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+set -o errtrace
+
+############################################################################
+
 NEW_HOSTNAME="$1"
 
 if [ -z "$NEW_HOSTNAME" ]; then
-    echo "Usage: $0 <new hostname>"
+    echo "Usage: $0 <new hostname>" 1>&2
     exit 1
 fi
 
-IP_ADDRESS=$(perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 2>/dev/null)
-
-if [ $? -ne 0 ]; then
-    echo "Error: Unable to determine an IP address for $NEW_HOSTNAME."
+if ! perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 1>/dev/null 2>/dev/null ; then
+    echo "Error: Unable to determine an IP address for: $NEW_HOSTNAME" 1>&2
     exit 1
 fi
 
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: This utility must be run as root. Perhaps use 'sudo'."
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
-
-echo "Beginning to configure $NEW_HOSTNAME as the web host"
 
 #
 # Simple function for abstracting out the invocation of 'sed'.
@@ -42,7 +44,7 @@ function update_config() {
     val=${val//\//\\\/}
 
     if [ -r "$target" ]; then
-        echo "Updating $target ($key)"
+        echo "Updating: $target: $key"
         if [ "$nospace" = "-nospace" ]; then
             sed -i "s/^\s*$key\s*=.*$/$key=$val/" "$target"
         else
@@ -72,18 +74,17 @@ done
 #
 target="/var/www/html/config/config.json"
 
-if [ -r "$target" ]; then
-    echo "Updating $target"
+if [ -f "$target" ]; then
+    echo "Updating: $target"
     /opt/swamp/sbin/swamp_set_config_json_host "$NEW_HOSTNAME"
 fi
 
 #
 # Update database
 #
-TMP_FILE=`mktemp /tmp/swamp_set_web_host.XXXXXX.sql`
-OUTGOING_URL="https://$NEW_HOSTNAME/results/"
+TMP_FILE=$(mktemp /tmp/swamp_set_web_host.XXXXXX.sql)
 
-trap 'rm -f $TMP_FILE' INT TERM
+trap 'rm -f $TMP_FILE; exit 1' INT TERM
 
 cat >"$TMP_FILE" <<END_DB_SCRIPT
     DELETE FROM assessment.system_setting WHERE system_setting_code='OUTGOING_BASE_URL';
@@ -96,4 +97,4 @@ echo "Updating database records"
 /opt/swamp/sbin/execute_sql_script "$TMP_FILE"
 rm -f "$TMP_FILE"
 
-echo "Finished configuring $NEW_HOSTNAME as the web host"
+exit $encountered_error
diff --git a/swampinabox/runtime/sbin/create_mysql_root_cnf b/swampinabox/runtime/sbin/create_mysql_root_cnf
--- a/swampinabox/runtime/sbin/create_mysql_root_cnf
+++ b/swampinabox/runtime/sbin/create_mysql_root_cnf
@@ -7,40 +7,69 @@
 
 #
 # Create a configuration file for use with 'mysql --defaults-file'
-# that logs in as the database 'root' user.
+# for logging into the database as the given user ('root' by default).
 #
 
-src_file="/etc/.mysql_root"
 dest_file="$1"
-
-if [ ! -r "$src_file" ]; then
-    echo "Error: $src_file is not readable"
-    exit 1
-fi
+src_file="$2"
+db_user="$3"
 
 if [ -z "$dest_file" ]; then
-    echo "Usage: $0 <destination file>"
+    echo "Usage: $0 <destination file> [password file] [database user]" 1>&2
     exit 1
 fi
 
 if [ -e "$dest_file" ]; then
-    echo "Error: $dest_file already exists"
+    echo "Error: $0: Already exists: $dest_file" 1>&2
+    exit 1
+fi
+
+if [ ! -z "$src_file" -a ! -r "$src_file" ]; then
+    echo "Error: $0: Unable to read password file: $src_file" 1>&2
     exit 1
 fi
 
 #
+# For the password file, try a couple of defaults.
+#
+
+if [ -z "$src_file" ]; then
+    src_file="/etc/.mysql_root"
+fi
+
+if [ ! -r "$src_file" ]; then
+    src_file="/etc/.mysql"
+fi
+
+if [ ! -r "$src_file" ]; then
+    echo "Error: $0: Unable to read password file" 1>&2
+    exit 1
+fi
+
+#
+# For the database user, default to 'root'.
+#
+
+if [ -z "$db_user" ]; then
+    db_user="root"
+fi
+
+#
 # In the options file for MySQL:
-#   - Quote the password, in case it contains '#'.
+#   - Quote values, in case they contain '#'.
 #   - Escape backslashes (the only character that needs escaping).
 #
 # See: http://dev.mysql.com/doc/refman/5.7/en/option-files.html
 #
-dbroot=`openssl enc -d -aes-256-cbc -in /etc/.mysql_root -pass pass:swamp`
-dbroot=${dbroot//\\/\\\\}
+db_user=${db_user//\\/\\\\}
+db_password=$(openssl enc -d -aes-256-cbc -in "$src_file" -pass pass:swamp)
+db_password=${db_password//\\/\\\\}
 
+umask 077
 touch "$dest_file"
-chmod 400 "$dest_file"
+chmod 600 "$dest_file"
 
-echo '[client]' > "$dest_file"
-echo "password='$dbroot'" >> "$dest_file"
-echo "user='root'" >> "$dest_file"
+echo "[client]" > "$dest_file"
+echo "password='$db_password'" >> "$dest_file"
+echo "user='$db_user'" >> "$dest_file"
+chmod 400 "$dest_file"
diff --git a/swampinabox/runtime/sbin/execute_sql_script b/swampinabox/runtime/sbin/execute_sql_script
--- a/swampinabox/runtime/sbin/execute_sql_script
+++ b/swampinabox/runtime/sbin/execute_sql_script
@@ -6,15 +6,22 @@
 # Copyright 2012-2017 Software Assurance Marketplace
 
 #
-# Execute a SQL script as the database 'root' user.
+# Execute a SQL script as the database's 'root' user.
 #
 
 script_file="$1"
 cnf_file="/opt/swamp/sql/sql.cnf"
+cnf_file_needs_removal="no"
+started_mysql_service="no"
 
 function do_clean_up {
     stty echo
-    rm -f "$cnf_file"
+    if [ "$cnf_file_needs_removal" != "no" ]; then
+        rm -f "$cnf_file"
+    fi
+    if [ "$started_mysql_service" != "no" ]; then
+        /opt/swamp/sbin/swamp_manage_service mysql stop
+    fi
 }
 
 function exit_normally {
@@ -24,7 +31,7 @@ function exit_normally {
 
 function exit_with_error {
     do_clean_up
-    echo "$0: Error while attempting to execute $script_file"
+    echo "Error: $0: Error while attempting to execute: $script_file" 1>&2
     exit 1
 }
 
@@ -36,44 +43,43 @@ trap 'exit_with_error' INT TERM
 ############################################################################
 
 if [ -z "$script_file" ]; then
-    echo "Usage: $0 <SQL script file>"
+    echo "Usage: $0 <SQL script file>" 1>&2
     exit 1
 fi
 
 if [ ! -r "$script_file" ]; then
-    echo "Error: $script_file is not readable"
+    echo "Error: $0: No such file (or file is not readable): $script_file" 1>&2
     exit 1
 fi
 
-started_mysql_service="no"
 initial_mysql_service_status=$(/opt/swamp/sbin/swamp_manage_service mysql status)
 
-if [ "$initial_mysql_service_status" = "stopped" ]; then
-    /opt/swamp/sbin/swamp_manage_service mysql start
-    started_mysql_service="yes"
+if [ $? -ne 0 ]; then
+    exit_with_error
 fi
 
-if [ -r /etc/.mysql_root ]; then
+if [ "$initial_mysql_service_status" = "stopped" ]; then
+    started_mysql_service="yes"
+    /opt/swamp/sbin/swamp_manage_service mysql start || exit_with_error
+fi
+
+if [ -r /etc/.mysql_root -o -r /etc/.mysql ]; then
     # Allow for the possibility that we're running in a context
     # where the configuration file has already been created.
 
-    if [ ! -r "$cnf_file" ]; then
-        /opt/swamp/sbin/create_mysql_root_cnf "$cnf_file" || exit_with_error
+    if [ ! -e "$cnf_file" ]; then
         cnf_file_needs_removal="yes"
+        /opt/swamp/sbin/create_mysql_root_cnf "$cnf_file" || exit_with_error
     fi
 
     mysql --defaults-file="$cnf_file" < "$script_file" || exit_with_error
 
-    if [ "$cnf_file_needs_removal" == "yes" ]; then
+    if [ "$cnf_file_needs_removal" != "no" ]; then
         rm -f "$cnf_file"
     fi
 else
-    echo "Enter the password for the database 'root' user"
+    echo "Enter the password for the database's 'root' user:"
     mysql -u root -p < "$script_file" || exit_with_error
-fi
-
-if [ "$started_mysql_service" = "yes" ]; then
-    /opt/swamp/sbin/swamp_manage_service mysql stop
 fi
 
 exit_normally
