1.33.246.siab_Production_Build

diff --git a/swampinabox/runtime/bin/install_codedx b/swampinabox/runtime/bin/install_codedx
--- a/swampinabox/runtime/bin/install_codedx
+++ b/swampinabox/runtime/bin/install_codedx
@@ -5,42 +5,100 @@
 #
 # Copyright 2012-2018 Software Assurance Marketplace
 
-codedx_src_file="$1"
-codedx_dest_file="/opt/swamp/thirdparty/codedx/vendor/codedx.war"
-codedx_install_sql="/opt/swamp/sql/install_codedx.sql"
+#
+# Install Code Dx.
+#
 
-function exit_with_error {
-    echo ""
-    echo "Failed to completely install Code Dx "
-    exit 1
+encountered_error=0
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
+set -o errtrace
+
+codedx_root="/opt/swamp/thirdparty/codedx"
+codedx_swamp="$codedx_root/swamp"
+codedx_vendor="$codedx_root/vendor"
+
+BINDIR="$(dirname "$0")"
+codedx_src="$1"
+codedx_dest="$codedx_vendor/codedx.war"
+codedx_install_sql="/opt/swamp/sql/install_codedx.sql"
+codedx_emptydb=""
+codedx_version=""
+codedx_properties="WEB-INF/classes/version.properties"
+
+############################################################################
+
+function set_codedx_version() {
+    war_file="$1"
+
+    if [ ! -r "$war_file" ]; then
+        echo "Error: Unable to read: $war_file" 1>&2
+        exit 1
+    fi
+    if ! unzip -l "$war_file" "$codedx_properties" 1>/dev/null 2>/dev/null ; then
+        echo "Error: Not a recognized Code Dx .war file: $war_file" 1>&2
+        exit 1
+    fi
+
+    codedx_version=$(unzip -p "$war_file" "$codedx_properties" | \
+                     grep -E '^\s*version\s*=' | \
+                     head -n 1 | \
+                     sed -E -e 's/^\s*version\s*=\s*//')
+    codedx_emptydb="emptydb-codedx-${codedx_version}.sql"
+
+    if [ ! -f "$codedx_swamp/$codedx_emptydb" ]; then
+        echo "Error: Not a supported version of Code Dx: $codedx_version" 1>&2
+        exit 1
+    fi
 }
 
-if [ ! -e "$codedx_dest_file" -a -z "$codedx_src_file" ]; then
-    echo "Usage: $0 <Code Dx .war file>"
+############################################################################
+
+#
+# The source file is optional if the destination already exists.
+# However, when provided, the source file takes priority.
+#
+if [ -e "$codedx_dest" ] && [ ! -f "$codedx_dest" ]; then
+    echo "Error: Already exists, but is not a regular file: $codedx_dest" 1>&2
+    exit 1
+fi
+if [ ! -f "$codedx_dest" ] && [ -z "$codedx_src" ]; then
+    echo "Usage: $0 <Code Dx .war file>" 1>&2
+    exit 1
+fi
+if [ ! -z "$codedx_src" ] && [ ! -f "$codedx_src" ]; then
+    echo "Error: No such file: $codedx_src" 1>&2
     exit 1
 fi
 
-if [ ! -z "$codedx_src_file" -a ! -e "$codedx_src_file" ]; then
-    echo "Error: $codedx_src_file does not exist"
-    exit 1
+if [ -f "$codedx_src" ]; then
+    set_codedx_version "$codedx_src"
+elif [ -f "$codedx_dest" ]; then
+    set_codedx_version "$codedx_dest"
 fi
 
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: The install must be performed as root."
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
-if [ -e "$codedx_src_file" ]; then
-    echo ""
-    echo "Installing $codedx_src_file into /opt/swamp ..."
+############################################################################
 
-    install -m 444 "$codedx_src_file" "$codedx_dest_file" || exit_with_error
+if [ -f "$codedx_src" ] && [ ! \( "$codedx_src" -ef "$codedx_dest" \) ]; then
+    echo "Copying '$codedx_src' to '$(dirname "$codedx_dest")'"
+    install -m 0444 "$codedx_src" "$codedx_dest"
 fi
 
-echo ""
-echo "Adding database entries for Code Dx ..."
+echo "Setting up empty Code Dx database for version $codedx_version"
+ln -sf "$codedx_emptydb" "$codedx_swamp/emptydb-codedx.sql"
 
-/opt/swamp/sbin/execute_sql_script "$codedx_install_sql" || exit_with_error
+echo "Adding SWAMP database entries for Code Dx"
+"$BINDIR/../sbin/execute_sql_script" "$codedx_install_sql"
 
-echo ""
-echo "Code Dx should now be available for viewing assessment results."
+############################################################################
+
+if [ $encountered_error -eq 0 ]; then
+    echo "Finished installing Code Dx"
+else
+    echo "Error: Finished installing Code Dx, but with errors" 1>&2
+fi
+exit $encountered_error
diff --git a/swampinabox/runtime/bin/install_platform b/swampinabox/runtime/bin/install_platform
--- a/swampinabox/runtime/bin/install_platform
+++ b/swampinabox/runtime/bin/install_platform
@@ -9,103 +9,19 @@
 # Install a VM disk image as a new platform for assessments.
 #
 
+encountered_error=0
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
+set -o errtrace
+
 ##########################################################################
 
 platforms_image_store="/swamp/platforms/images"
 platforms_script_store="/opt/swamp/sql/platforms"
-vm_image_src="$1"
+
+BINDIR=$(dirname "$0")
+vm_image_src=$1
 vm_image_dest="$platforms_image_store/$(basename "$vm_image_src")"
-
-##########################################################################
-
-mysql_passwd_file="/etc/.mysql_root"
-mysql_cnf_file="/opt/swamp/sql/sql.cnf"
-
-function do_clean_up {
-    stty echo
-    rm -f "$mysql_cnf_file"
-    rm -f "$mysql_passwd_file"
-}
-
-function exit_normally {
-    do_clean_up
-    exit 0
-}
-
-function exit_with_error {
-    do_clean_up
-    echo "$0: Error while attempting to install: $vm_image_src" 1>&2
-    exit 1
-}
-
-#
-# Ensure that temporary files get removed.
-#
-trap 'exit_with_error' INT TERM
-
-##########################################################################
-
-ask_pass() {
-    prompt="$1"
-    if [ "$2" = "-confirm" ]; then need_confirm=1; else need_confirm=0; fi
-    need_password=1
-
-    while [ "$need_password" -eq 1 ]; do
-        ANSWER=""
-        CONFIRMATION=""
-
-        read -r -s -p "$prompt " ANSWER
-        echo
-
-        if [ -z "$ANSWER" ]; then
-            echo "*** Password cannot be empty. ***"
-        else
-            if [ "$need_confirm" -eq 1 ]; then
-                read -r -s -p "Retype password: " CONFIRMATION
-                echo
-
-                if [ "$ANSWER" != "$CONFIRMATION" ]; then
-                    echo "*** Passwords do not match. ***"
-                else
-                    need_password=0
-                fi
-            else
-                need_password=0
-            fi
-        fi
-    done
-}
-
-function save_password_to_disk() {
-    destination="$1"
-    password="$2"
-
-    reset_umask="$(umask -p)"
-    umask 377
-
-    rm -f "$destination"
-    echo "$password" | sudo openssl enc -aes-256-cbc -salt -out "$destination" -pass pass:swamp
-    chmod 400 "$destination"
-
-    $reset_umask
-}
-
-function test_db_password() {
-    username="$1"
-    password="$2"
-    encountered_error=0
-
-    save_password_to_disk "$mysql_passwd_file" "$password"
-    /opt/swamp/sbin/create_mysql_root_cnf "$mysql_cnf_file" "$mysql_passwd_file" "$username"
-
-    if ! mysql --defaults-file="$mysql_cnf_file" <<< ';' ; then
-        echo "Error: Failed to log into the database as '$username'" 1>&2
-        encountered_error=1
-    fi
-
-    do_clean_up
-    return $encountered_error
-}
+vm_image_dest="${vm_image_dest%%.gz}"
 
 ##########################################################################
 
@@ -113,13 +29,11 @@ if [ -z "$vm_image_src" ]; then
     echo "Usage: $0 <VM platform .qcow2 or .qcow2.gz file>" 1>&2
     exit 1
 fi
-
 if [ ! -r "$vm_image_src" ]; then
-    echo "Error: File does not exist or is not readable: $vm_image_src" 1>&2
+    echo "Error: File is not readable: $vm_image_src" 1>&2
     exit 1
 fi
-
-if [[ ! ( "$vm_image_src" =~ .qcow2$ ) && ! ( "$vm_image_src" =~ .qcow2.gz$ ) ]]; then
+if [[ ! ( "$vm_image_src" =~ \.qcow2$ ) && ! ( "$vm_image_src" =~ \.qcow2\.gz$ ) ]]; then
     echo "Error: Not a '.qcow2' or 'qcow2.gz' file: $vm_image_src" 1>&2
     exit 1
 fi
@@ -144,51 +58,51 @@ if [ -z "$platform_install_sql" ]; then
     echo "Error: Not a recognized installable platform: $vm_image_src" 1>&2
     exit 1
 fi
-
 if [ "$(whoami)" != "root" ]; then
     echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
-##########################################################################
-
-success=1
-while [ $success -ne 0 ]; do
-    ask_pass "Enter database root password:"
-    DBROOT="$ANSWER"
-
-    test_db_password root "$DBROOT"
-    success=$?
-done
+source "$BINDIR/../sbin/db_support.functions"
+trap 'stty echo ; reset_db_support' EXIT
+trap 'stty echo ; reset_db_support ; exit 1' INT TERM
 
 ##########################################################################
 
-if [[ "$vm_image_src" =~ .qcow2$ ]]; then
-    echo "Copying '$(basename "$vm_image_src")' to '$platforms_image_store'"
+#
+# Prompt early for the database root password, so that the user can
+# wander off while the .qcow2 file is installed on the file system.
+#
+setup_db_support
 
-    cp    "$vm_image_src" "$vm_image_dest" || exit_with_error
-    chown root:root       "$vm_image_dest" || exit_with_error
-    chmod 644             "$vm_image_dest" || exit_with_error
+#
+# Install the .qcow2 file.
+#
+if [ "$vm_image_src" != "$vm_image_dest" ]; then
+    if [[ "$vm_image_src" =~ .qcow2$ ]]; then
+        echo "Copying '$(basename "$vm_image_src")' to '$(dirname "$vm_image_dest")'"
+        cp "$vm_image_src" "$vm_image_dest"
+    elif [[ "$vm_image_src" =~ .gz$ ]]; then
+        echo "Unzipping '$(basename "$vm_image_src")' into '$(dirname "$vm_image_dest")'"
+        gunzip -c "$vm_image_src" > "$vm_image_dest"
+    fi
 fi
+chown root:root "$vm_image_dest"
+chmod 644       "$vm_image_dest"
 
-if [[ "$vm_image_src" =~ .gz$ ]]; then
-    echo "Unzipping '$(basename "$vm_image_src")' into '$platforms_image_store'"
-
-    vm_image_dest=${vm_image_dest%%.gz}
-
-    gunzip -c "$vm_image_src" > "$vm_image_dest" || exit_with_error
-    chown root:root  "$vm_image_dest" || exit_with_error
-    chmod 644        "$vm_image_dest" || exit_with_error
-fi
-
-##########################################################################
-
+#
+# Update the database.
+#
 echo "Updating database records"
-
-save_password_to_disk "$mysql_passwd_file" "$DBROOT"       || exit_with_error
-/opt/swamp/sbin/execute_sql_script "$platform_install_sql" || exit_with_error
+do_mysql_command "$platform_install_sql"
 
 ##########################################################################
 
-echo "Install completed normally"
-exit_normally
+reset_db_support
+
+if [ $encountered_error -eq 0 ]; then
+    echo "Finished installing platform"
+else
+    echo "Error: Finished installing platform, but with errors"
+fi
+exit $encountered_error
diff --git a/swampinabox/runtime/bin/swamp_check_virtualization_support b/swampinabox/runtime/bin/swamp_check_virtualization_support
--- a/swampinabox/runtime/bin/swamp_check_virtualization_support
+++ b/swampinabox/runtime/bin/swamp_check_virtualization_support
@@ -10,33 +10,65 @@
 #
 
 encountered_error=0
-trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
 set -o errtrace
 
-##########################################################################
+############################################################################
 
+function has_amd_svm_flag() {
+    grep -i -E '\<svm\>' /proc/cpuinfo 1>/dev/null 2>/dev/null
+}
+
+function has_intel_vmx_flag() {
+    grep -i -E '\<vmx\>' /proc/cpuinfo 1>/dev/null 2>/dev/null
+}
+
+#
+# If running as 'root', display information that might be helpful in
+# determining whether the host is running on bare metal versus in a virtual
+# machine.
+#
 if which dmidecode 1>/dev/null 2>/dev/null ; then
     if [ "$(whoami)" = "root" ]; then
         echo "Looking for system manufacturer ... $(dmidecode -s system-manufacturer)"
         echo "Looking for system product name ... $(dmidecode -s system-product-name)"
+        echo ""
     fi
 fi
 
-##########################################################################
-
-if grep -E '(vmx|svm)' /proc/cpuinfo 1>/dev/null 2>/dev/null ; then
-    echo "Looking for Intel Virtual Technology CPU extensions ... found"
+#
+# Check that the necessary CPU extensions (flags) are present.
+#
+if has_amd_svm_flag ; then
+    echo "Checking for CPU virtualization extensions ... found svm"
+elif has_intel_vmx_flag ; then
+    echo "Checking for CPU virtualization extensions ... found vmx"
 else
-    echo "Error: Looking for Intel Virtual Technology CPU extensions ... not found"
-    echo "Try enabling Intel Virtual Technology extensions in the BIOS."
+    echo "Error: Checking for CPU virtualization extensions ... not found" 1>&2
+    echo "Perhaps try enabling Intel Virtual Technology extensions in the BIOS." 1>&2
     exit 1
 fi
 
-if lsmod | grep kvm 1>/dev/null 2>/dev/null ; then
-    echo "Looking for 'kvm' kernel modules ... loaded"
+#
+# Check that the 'kvm' kernel modules are loaded.
+#
+if lsmod | grep -E '\<kvm\>' 1>/dev/null 2>/dev/null ; then
+    echo "Checking for the kvm kernel module ... loaded"
 else
-    echo "Error: Looking for 'kvm' kernel modules ... not loaded"
-    echo "Try loading the 'kvm' kernel module."
+    echo "" 1>&2
+    echo "Error: Checking for the kvm kernel module ... not loaded" 1>&2
+    echo "Perhaps try loading the 'kvm' kernel module." 1>&2
+    exit 1
+fi
+if lsmod | grep -E '\<kvm_amd\>' 1>/dev/null 2>/dev/null ; then
+    echo "Checking for the kvm_amd or kvm_intel kernel module ... kvm_amd loaded"
+elif lsmod | grep -E '\<kvm_intel\>' 1>/dev/null 2>/dev/null ; then
+    echo "Checking for the kvm_amd or kvm_intel kernel module ... kvm_intel loaded"
+else
+    echo "" 1>&2
+    echo "Error: Checking for the kvm_amd or kvm_intel kernel module ... not loaded" 1>&2
+    if has_amd_svm_flag ; then echo "Perhaps try loading the 'kvm_amd' kernel module." 1>&2 ; fi
+    if has_intel_vmx_flag ; then echo "Perhaps try loading the 'kvm_intel' kernel module." 1>&2 ; fi
     exit 1
 fi
 
diff --git a/swampinabox/runtime/bin/swamp_set_db_host b/swampinabox/runtime/bin/swamp_set_db_host
--- a/swampinabox/runtime/bin/swamp_set_db_host
+++ b/swampinabox/runtime/bin/swamp_set_db_host
@@ -10,41 +10,69 @@
 #
 
 encountered_error=0
-trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
 set -o errtrace
+
+function show_usage_and_exit() {
+    echo "Usage: $0 --hostname=<new hostname>" 1>&2
+    exit 1
+}
+
+dot_env="/var/www/swamp-web-server/.env"
+swamp_conf="/opt/swamp/etc/swamp.conf"
 
 ############################################################################
 
-NEW_HOSTNAME="$1"
+new_hostname=""
 
-if [ -z "$NEW_HOSTNAME" ]; then
-    echo "Usage: $0 <new hostname>" 1>&2
+for option in "$@" ; do
+    case "$option" in
+        --hostname=*) new_hostname=${option#--hostname=} ;;
+        --help)
+            show_usage_and_exit
+            ;;
+        *)
+            echo "Error: Unrecognized option: $option" 1>&2
+            echo "" 1>&2
+            show_usage_and_exit
+            ;;
+    esac
+done
+
+if [ -z "$new_hostname" ]; then
+    show_usage_and_exit
+fi
+if ! perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$new_hostname" 1>/dev/null 2>/dev/null ; then
+    echo "Error: Unable to determine an IP address for: $new_hostname" 1>&2
     exit 1
 fi
-
-if ! perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 1>/dev/null 2>/dev/null ; then
-    echo "Error: Unable to determine an IP address for: $NEW_HOSTNAME" 1>&2
+if [ ! -f "$dot_env" ]; then
+    echo "Error: No such file: $dot_env" 1>&2
     exit 1
 fi
-
+if [ ! -f "$swamp_conf" ]; then
+    echo "Error: No such file: $swamp_conf" 1>&2
+    exit 1
+fi
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: This utility must be run as root. Perhaps use 'sudo'." 1>&2
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
-#
-# Simple function for abstracting out the invocation of 'sed'.
-#
+############################################################################
+
 function update_config() {
     key="$1"
     val="$2"
     target="$3"
     nospace="$4"
 
-    val=${val//\//\\\/}
+    # Escape special characters for sed's 's//'
+    val=${val//\\/\\\\}  # escape back slash
+    val=${val//\//\\\/}  # escape forward slash
+    val=${val//&/\\&}    # escape ampersands
 
-    if [ -r "$target" ]; then
-        echo "Updating: $target: $key"
+    if [ -f "$target" ]; then
         if [ "$nospace" = "-nospace" ]; then
             sed -i "s/^\s*$key\s*=.*$/$key=$val/" "$target"
         else
@@ -53,20 +81,14 @@ function update_config() {
     fi
 }
 
-#
-# Update swamp.conf (backend)
-#
-target="/opt/swamp/etc/swamp.conf"
+echo "Setting database host to $new_hostname"
 
-update_config "dbPerlDsnHost" "$NEW_HOSTNAME" "$target"
-
-#
-# Update .env (web server)
-#
-target="/var/www/swamp-web-server/.env"
-
-for key in ASSESSMENT_DB_HOST PACKAGE_DB_HOST PLATFORM_DB_HOST PROJECT_DB_HOST TOOL_DB_HOST VIEWER_DB_HOST; do
-    update_config "$key" "$NEW_HOSTNAME" "$target" -nospace
-done
+update_config dbPerlDsnHost      "$new_hostname" "$swamp_conf"
+update_config ASSESSMENT_DB_HOST "$new_hostname" "$dot_env" -nospace
+update_config PACKAGE_DB_HOST    "$new_hostname" "$dot_env" -nospace
+update_config PLATFORM_DB_HOST   "$new_hostname" "$dot_env" -nospace
+update_config PROJECT_DB_HOST    "$new_hostname" "$dot_env" -nospace
+update_config TOOL_DB_HOST       "$new_hostname" "$dot_env" -nospace
+update_config VIEWER_DB_HOST     "$new_hostname" "$dot_env" -nospace
 
 exit $encountered_error
diff --git a/swampinabox/runtime/bin/swamp_set_htcondor_host b/swampinabox/runtime/bin/swamp_set_htcondor_host
--- a/swampinabox/runtime/bin/swamp_set_htcondor_host
+++ b/swampinabox/runtime/bin/swamp_set_htcondor_host
@@ -6,47 +6,75 @@
 # Copyright 2012-2018 Software Assurance Marketplace
 
 #
-# Set the hostname of the HTCondor installation in all relevant
-# configuration locations. There's an implicit assumption here that the
-# entire installation is running on one host.
+# Set the hostname of the HTCondor collector in all relevant configuration
+# locations. This script assumes that the pool is running on a single host.
 #
 
 encountered_error=0
-trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
 set -o errtrace
+
+function show_usage_and_exit() {
+    echo "Usage: $0 --hostname=<new hostname>" 1>&2
+    exit 1
+}
+
+BINDIR=$(dirname "$0")
+dot_env="/var/www/swamp-web-server/.env"
+swamp_conf="/opt/swamp/etc/swamp.conf"
 
 ############################################################################
 
-NEW_HOSTNAME="$1"
+new_hostname=""
 
-if [ -z "$NEW_HOSTNAME" ]; then
-    echo "Usage: $0 <new hostname>" 1>&2
+for option in "$@" ; do
+    case "$option" in
+        --hostname=*) new_hostname=${option#--hostname=} ;;
+        --help)
+            show_usage_and_exit
+            ;;
+        *)
+            echo "Error: Unrecognized option: $option" 1>&2
+            echo "" 1>&2
+            show_usage_and_exit
+            ;;
+    esac
+done
+
+if [ -z "$new_hostname" ]; then
+    show_usage_and_exit
+fi
+if ! perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$new_hostname" 1>/dev/null 2>/dev/null ; then
+    echo "Error: Unable to determine an IP address for: $new_hostname" 1>&2
     exit 1
 fi
-
-if ! IP_ADDRESS=$(perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 2>/dev/null) ; then
-    echo "Error: Unable to determine an IP address for: $NEW_HOSTNAME" 1>&2
+if [ ! -f "$dot_env" ]; then
+    echo "Error: No such file: $dot_env" 1>&2
     exit 1
 fi
-
+if [ ! -f "$swamp_conf" ]; then
+    echo "Error: No such file: $swamp_conf" 1>&2
+    exit 1
+fi
 if [ "$(whoami)" != "root" ]; then
     echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
-#
-# Simple function for abstracting out the invocation of 'sed'.
-#
+############################################################################
+
 function update_config() {
     key="$1"
     val="$2"
     target="$3"
     nospace="$4"
 
-    val=${val//\//\\\/}
+    # Escape special characters for sed's 's//'
+    val=${val//\\/\\\\}  # escape back slash
+    val=${val//\//\\\/}  # escape forward slash
+    val=${val//&/\\&}    # escape ampersands
 
-    if [ -r "$target" ]; then
-        echo "Updating: $target: $key"
+    if [ -f "$target" ]; then
         if [ "$nospace" = "-nospace" ]; then
             sed -i "s/^\s*$key\s*=.*$/$key=$val/" "$target"
         else
@@ -55,34 +83,15 @@ function update_config() {
     fi
 }
 
-#
-# Update swamp.conf (backend)
-#
-target="/opt/swamp/etc/swamp.conf"
+echo "Setting HTCondor host to $new_hostname"
 
-update_config "htcondor_collector_host" "$NEW_HOSTNAME" "$target"
+update_config "htcondor_collector_host" "$new_hostname" "$swamp_conf"
+update_config "HTCONDOR_COLLECTOR_HOST" "$new_hostname" "$dot_env" -nospace
 
-#
-# Update .env (web server)
-#
-target="/var/www/swamp-web-server/.env"
-
-update_config "HTCONDOR_COLLECTOR_HOST" "$NEW_HOSTNAME" "$target" -nospace
-
-#
-# Update /etc/condor/config.d (HTCondor itself)
-#
-update_config "NETWORK_INTERFACE" "$IP_ADDRESS"   "/etc/condor/config.d/swampinabox_10_network.conf"
-update_config "NETWORK_HOSTNAME"  "$NEW_HOSTNAME" "/etc/condor/config.d/swampinabox_10_network.conf"
-update_config "CONDOR_HOST"       "$NEW_HOSTNAME" "/etc/condor/config.d/swampinabox_20_main.conf"
-update_config "UID_DOMAIN"        "$NEW_HOSTNAME" "/etc/condor/config.d/swampinabox_30_jobcontrol.conf"
-update_config "ALLOW_WRITE"       "$NEW_HOSTNAME" "/etc/condor/config.d/swampinabox_30_jobcontrol.conf"
-
-htcondor_service_status=$(/opt/swamp/sbin/swamp_manage_service condor status)
-
+htcondor_service_status=$("$BINDIR/../sbin/swamp_manage_service" condor status)
 if [ "$htcondor_service_status" = "running" ]; then
-    echo "Restarting service: condor"
-    /opt/swamp/sbin/swamp_manage_service condor restart
+    echo "Restarting HTCondor daemons"
+    condor_restart
 fi
 
 exit $encountered_error
diff --git a/swampinabox/runtime/bin/swamp_set_web_host b/swampinabox/runtime/bin/swamp_set_web_host
--- a/swampinabox/runtime/bin/swamp_set_web_host
+++ b/swampinabox/runtime/bin/swamp_set_web_host
@@ -10,41 +10,89 @@
 #
 
 encountered_error=0
-trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
 set -o errtrace
+
+function show_usage_and_exit() {
+    echo "Usage: $0 --hostname=<new hostname> [options]" 1>&2
+    echo "" 1>&2
+    echo "Options:" 1>&2
+    echo "  --force  Do not configure relative URLs anywhere" 1>&2
+    exit 1
+}
+
+BINDIR=$(dirname "$0")
+config_json="/var/www/html/config/config.json"
+dot_env="/var/www/swamp-web-server/.env"
+swamp_conf="/opt/swamp/etc/swamp.conf"
 
 ############################################################################
 
-NEW_HOSTNAME="$1"
+new_hostname=""
+set_hostname_everywhere=""
 
-if [ -z "$NEW_HOSTNAME" ]; then
-    echo "Usage: $0 <new hostname>" 1>&2
+for option in "$@" ; do
+    case "$option" in
+        --force) set_hostname_everywhere="yes" ;;
+        --hostname=*) new_hostname=${option#--hostname=} ;;
+        --help)
+            show_usage_and_exit
+            ;;
+        *)
+            echo "Error: Unrecognized option: $option" 1>&2
+            echo "" 1>&2
+            show_usage_and_exit
+            ;;
+    esac
+done
+
+if [ -z "$new_hostname" ]; then
+    show_usage_and_exit
+fi
+if ! perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$new_hostname" 1>/dev/null 2>/dev/null ; then
+    echo "Error: Unable to determine an IP address for: $new_hostname" 1>&2
     exit 1
 fi
-
-if ! perl -e 'use Socket; print inet_ntoa(inet_aton($ARGV[0]))' "$NEW_HOSTNAME" 1>/dev/null 2>/dev/null ; then
-    echo "Error: Unable to determine an IP address for: $NEW_HOSTNAME" 1>&2
+if [ ! -f "$config_json" ]; then
+    echo "Error: No such file: $config_json" 1>&2
     exit 1
 fi
-
+if [ ! -f "$dot_env" ]; then
+    echo "Error: No such file: $dot_env" 1>&2
+    exit 1
+fi
+if [ ! -f "$swamp_conf" ]; then
+    echo "Error: No such file: $swamp_conf" 1>&2
+    exit 1
+fi
 if [ "$(whoami)" != "root" ]; then
     echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
-#
-# Simple function for abstracting out the invocation of 'sed'.
-#
+############################################################################
+
+default_web_server=""
+laravel_app_url="https://$new_hostname"
+swamp_api_web_server="https://localhost"
+
+if [ "$set_hostname_everywhere" = "yes" ]; then
+    default_web_server="https://$new_hostname"
+    swamp_api_web_server="https://$new_hostname"
+fi
+
 function update_config() {
     key="$1"
     val="$2"
     target="$3"
     nospace="$4"
 
-    val=${val//\//\\\/}
+    # Escape special characters for sed's 's//'
+    val=${val//\\/\\\\}  # escape back slash
+    val=${val//\//\\\/}  # escape forward slash
+    val=${val//&/\\&}    # escape ampersands
 
-    if [ -r "$target" ]; then
-        echo "Updating: $target: $key"
+    if [ -f "$target" ]; then
         if [ "$nospace" = "-nospace" ]; then
             sed -i "s/^\s*$key\s*=.*$/$key=$val/" "$target"
         else
@@ -54,48 +102,50 @@ function update_config() {
 }
 
 #
-# Update swamp.conf (backend)
+# SWAMP API web server (i.e., the backend web server).
 #
-target="/opt/swamp/etc/swamp.conf"
+"$BINDIR/../sbin/swamp_set_config_json_host" "$default_web_server"
 
-update_config "reporturl" "https://$NEW_HOSTNAME/results/" "$target"
-update_config "swamp_api_web_server" "$NEW_HOSTNAME/swamp-web-server/public" "$target"
-
-#
-# Update .env (web server)
-#
-target="/var/www/swamp-web-server/.env"
-
-for key in APP_URL APP_CORS_URL; do
-    update_config "$key" "https://$NEW_HOSTNAME" "$target" -nospace
-done
+echo "Setting SWAMP API web server in $(basename "$swamp_conf") to $swamp_api_web_server"
+update_config "swamp_api_web_server" "$swamp_api_web_server/swamp-web-server/public" "$swamp_conf"
 
 #
-# Update config.json (web server)
+# Laravel APP URLs.
 #
-target="/var/www/html/config/config.json"
+echo "Setting Laravel APP URLs to $laravel_app_url"
+update_config "APP_URL"      "$laravel_app_url" "$dot_env" -nospace
+update_config "APP_CORS_URL" "$laravel_app_url" "$dot_env" -nospace
 
-if [ -f "$target" ]; then
-    echo "Updating: $target"
-    /opt/swamp/sbin/swamp_set_config_json_host "$NEW_HOSTNAME"
+#
+# Other places that affect how URLs are constructed for the web application.
+#
+if [ -z "$default_web_server" ]; then
+    echo "Setting web server in other URLs"
+else
+    echo "Setting web server in other URLs to $default_web_server"
 fi
+update_config "reporturl" "$default_web_server/results" "$swamp_conf"
 
 #
-# Update database
+# Updating the database entries requires a one-off script.
 #
 TMP_FILE=$(mktemp /tmp/swamp_set_web_host.XXXXXX.sql)
 
-trap 'rm -f $TMP_FILE; exit 1' INT TERM
+source "$BINDIR/../sbin/db_support.functions"
+trap 'rm -f "$TMP_FILE" ; stty echo ; reset_db_support' EXIT
+trap 'rm -f "$TMP_FILE" ; stty echo ; reset_db_support ; exit 1' INT TERM
+
+setup_db_support
 
 cat >"$TMP_FILE" <<END_DB_SCRIPT
     DELETE FROM assessment.system_setting WHERE system_setting_code='OUTGOING_BASE_URL';
     DELETE FROM assessment.system_setting WHERE system_setting_code='CODEDX_BASE_URL';
-    INSERT INTO assessment.system_setting (system_setting_code, system_setting_value) VALUES ('OUTGOING_BASE_URL', 'https://$NEW_HOSTNAME/results/');
-    INSERT INTO assessment.system_setting (system_setting_code, system_setting_value) VALUES ('CODEDX_BASE_URL', 'https://$NEW_HOSTNAME/');
+    INSERT INTO assessment.system_setting (system_setting_code, system_setting_value) VALUES ('OUTGOING_BASE_URL', '$default_web_server/results/');
+    INSERT INTO assessment.system_setting (system_setting_code, system_setting_value) VALUES ('CODEDX_BASE_URL', '$default_web_server/');
 END_DB_SCRIPT
 
-echo "Updating: Database records"
-/opt/swamp/sbin/execute_sql_script "$TMP_FILE"
+do_mysql_command "$TMP_FILE"
+reset_db_support
 rm -f "$TMP_FILE"
 
 exit $encountered_error
diff --git a/swampinabox/runtime/sbin/create_mysql_root_cnf b/swampinabox/runtime/sbin/create_mysql_root_cnf
--- a/swampinabox/runtime/sbin/create_mysql_root_cnf
+++ b/swampinabox/runtime/sbin/create_mysql_root_cnf
@@ -10,46 +10,54 @@
 # for logging into the database as the given user ('root' by default).
 #
 
-dest_file="$1"
-src_file="$2"
-db_user="$3"
+dest_file=$1
 
+allow_overwrite=""
+db_user=""
+src_file=""
+
+for option in "${@:2}" ; do
+    case "$option" in
+        --allow-overwrite) allow_overwrite="yes" ;;
+        --password-file=*) src_file=${option#--password-file=} ;;
+        --user=*)          db_user=${option#--user=} ;;
+    esac
+done
+
+if [ "$(whoami)" != "root" ]; then
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
+    exit 1
+fi
 if [ -z "$dest_file" ]; then
-    echo "Usage: $0 <destination file> [password file] [database user]" 1>&2
+    echo "Usage: $0 <destination file> [options]" 1>&2
     exit 1
 fi
-
-if [ -e "$dest_file" ]; then
-    echo "Error: $0: Already exists: $dest_file" 1>&2
+if [ -e "$dest_file" ] && [ "$allow_overwrite" != "yes" ]; then
+    echo "Error: Already exists: $dest_file" 1>&2
     exit 1
 fi
-
-if [ ! -z "$src_file" -a ! -r "$src_file" ]; then
-    echo "Error: $0: Unable to read password file: $src_file" 1>&2
+if [ ! -z "$src_file" ] && [ ! -r "$src_file" ]; then
+    echo "Error: Unable to read password file: $src_file" 1>&2
     exit 1
 fi
 
 #
 # For the password file, try a couple of defaults.
 #
-
 if [ -z "$src_file" ]; then
     src_file="/etc/.mysql_root"
 fi
-
 if [ ! -r "$src_file" ]; then
     src_file="/etc/.mysql"
 fi
-
 if [ ! -r "$src_file" ]; then
-    echo "Error: $0: Unable to read password file" 1>&2
+    echo "Error: Unable to read default password files" 1>&2
     exit 1
 fi
 
 #
 # For the database user, default to 'root'.
 #
-
 if [ -z "$db_user" ]; then
     db_user="root"
 fi
@@ -65,11 +73,11 @@ db_user=${db_user//\\/\\\\}
 db_password=$(openssl enc -d -aes-256-cbc -in "$src_file" -pass pass:swamp)
 db_password=${db_password//\\/\\\\}
 
-umask 077
+umask 0077
 touch "$dest_file"
-chmod 600 "$dest_file"
+chmod 0600 "$dest_file"
 
 echo "[client]" > "$dest_file"
-echo "password='$db_password'" >> "$dest_file"
 echo "user='$db_user'" >> "$dest_file"
-chmod 400 "$dest_file"
+echo "password='$db_password'" >> "$dest_file"
+chmod 0400 "$dest_file"
diff --git a/swampinabox/runtime/sbin/rebuild_platforms_db b/swampinabox/runtime/sbin/rebuild_platforms_db
--- a/swampinabox/runtime/sbin/rebuild_platforms_db
+++ b/swampinabox/runtime/sbin/rebuild_platforms_db
@@ -6,44 +6,39 @@
 # Copyright 2012-2018 Software Assurance Marketplace
 
 #
-# Rebuild the "platforms" tables in the database based on the
-# platform install SQL files available on the filesystem.
+# Rebuild the 'platforms' database.
 #
 
 encountered_error=0
-trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
 set -o errtrace
 
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: $0: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
 ############################################################################
 
+BINDIR=$(dirname "$0")
 platforms_image_store="/swamp/platforms/images"
 platforms_script_store="/opt/swamp/sql/platforms"
 platforms_delete_script="/opt/swamp/sql/util/delete_platforms.sql"
 
-. /opt/swamp/sbin/db_support.functions
-trap 'remove_mysql_options_file; stop_mysql_service; exit 1' INT TERM
+source "$BINDIR/db_support.functions"
+trap 'stty echo ; reset_db_support' EXIT
+trap 'stty echo ; reset_db_support ; exit 1' INT TERM
 
-start_mysql_service
-create_mysql_options_file
-
-############################################################################
-
-echo "Resetting database by removing existing platforms"
-
-if ! $mysql_command < "$platforms_delete_script" ; then
-    echo "Error: $0: Failed to remove existing platforms from the database" 1>&2
-    encountered_error=1
-fi
+setup_db_support
 
 ############################################################################
 
-echo "Searching for platforms to add to the database"
+echo "Resetting the platforms database by removing existing platforms"
+do_mysql_command "$platforms_delete_script"
 
+############################################################################
+
+echo "Adding platforms for the current release to the database"
 for platform_sql in "$platforms_script_store"/*.sql ; do
     platform=$(basename "$platform_sql" .sql)
     platform=${platform/\.minorversion/}
@@ -54,23 +49,25 @@ for platform_sql in "$platforms_script_store"/*.sql ; do
 
         for qcow_file in $platforms_image_store/condor-$distribution*$bits-master*.qcow2 ; do
             if [ -f "$qcow_file" ]; then
-
-                echo ".. Adding: $platform"
-
-                if ! $mysql_command < "$platform_sql" ; then
-                    echo "Error: $0: Failed to add: $platform (from: $platform_sql)" 1>&2
-                    encountered_error=1
-                fi
+                echo "Adding: $platform"
+                do_mysql_command "$platform_sql"
                 break
             fi
         done
     else
-        echo "Error: $0: Unable to identify platform: $platform_sql" 1>&2
+        echo "Error: Unable to identify platform: $platform_sql" 1>&2
         encountered_error=1
     fi
 done
+echo "Finished adding platforms to the database"
 
-remove_mysql_options_file
-stop_mysql_service
+############################################################################
 
+if [ $encountered_error -eq 0 ]; then
+    echo "Finished rebuilding the platforms database"
+else
+    echo "Error: Finished rebuilding the platforms database, but with errors" 1>&2
+fi
+
+reset_db_support
 exit $encountered_error
diff --git a/swampinabox/runtime/sbin/rebuild_tools_db b/swampinabox/runtime/sbin/rebuild_tools_db
--- a/swampinabox/runtime/sbin/rebuild_tools_db
+++ b/swampinabox/runtime/sbin/rebuild_tools_db
@@ -6,130 +6,102 @@
 # Copyright 2012-2018 Software Assurance Marketplace
 
 #
-# Rebuild the "tools" tables in the database.
+# Rebuild the 'tools' database.
 #
 
 encountered_error=0
-trap 'encountered_error=1; echo "Error: $0: $BASH_COMMAND" 1>&2' ERR
+trap 'encountered_error=1; echo "Error (unexpected): In $(basename "$0"): $BASH_COMMAND" 1>&2' ERR
 set -o errtrace
 
 if [ "$(whoami)" != "root" ]; then
-    echo "Error: $0: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
+    echo "Error: This utility must be run as 'root'. Perhaps use 'sudo'." 1>&2
     exit 1
 fi
 
 ############################################################################
 
-SWAMP_CONTEXT="$1"
+BINDIR=$(dirname "$0")
+swamp_context=$1
 
-source /opt/swamp/sbin/db_support.functions
-trap 'remove_mysql_options_file; stop_mysql_service; exit 1' INT TERM
+sql_temp=$(mktemp /tmp/rebuild_tools_db.XXXXXXXX)
 
-start_mysql_service
-create_mysql_options_file
+source "$BINDIR/db_support.functions"
+trap 'stty echo ; reset_db_support ; rm -f "$sql_temp"' EXIT
+trap 'stty echo ; reset_db_support ; rm -f "$sql_temp" ; exit 1' INT TERM
+
+setup_db_support
 
 ############################################################################
 
-tool_scripts_dirs=""
-tool_add_on_scripts_dir="/opt/swamp/sql/tools_add_on"
+function is_mir_swamp_like_context() {
+    [ "$swamp_context" = "-singleserver" ] || [ "$swamp_context" = "-mir-swamp" ]
+}
 
-tool_install_script="/opt/swamp/sql/util/tool_install.sql"
-tool_remove_all_script=""
-
-if [ "$SWAMP_CONTEXT" = -distribution ]; then
-
-    tool_scripts_dirs="/opt/swamp/sql/tools"
-    tool_remove_all_script="/opt/swamp/sql/util/delete_non_user_tools.sql"
-
-elif [ "$SWAMP_CONTEXT" = "-singleserver" -o "$SWAMP_CONTEXT" = "-mir-swamp" ]; then
-
-    tool_scripts_dirs="/opt/swamp/sql/tools /opt/swamp/sql/tools_other"
+if is_mir_swamp_like_context ; then
+    inventory_file_list=(tools-bundled.txt tools-metric.txt tools-MIR.txt)
     tool_remove_all_script="/opt/swamp/sql/util/delete_all_tools.sql"
-
 else
-
-    echo "Error: $0: Unknown or missing SWAMP context: $SWAMP_CONTEXT" 1>&2
-    exit 1
-
+    inventory_file_list=(tools-bundled.txt tools-metric.txt)
+    tool_remove_all_script="/opt/swamp/sql/util/delete_non_user_tools.sql"
 fi
 
 ############################################################################
 
-echo "Removing existing bundled tools from the database"
-
-if ! $mysql_command < "$tool_remove_all_script" ; then
-
-    echo "Error: $0: Failed to remove existing tools from the database" 1>&2
-    encountered_error=1
-
-fi
+echo "Resetting the tools database by removing existing bundled tools"
+do_mysql_command "$tool_remove_all_script"
 
 ############################################################################
 
 echo "Adding bundled tools for the current release to the database"
+for inventory_file in "${inventory_file_list[@]}" ; do
+    while read -r tool_archive ; do
+        tool_id=$(echo "$tool_archive" | sed -E -e 's/.gz$//' -e 's/.tar$//')
+        params_sql="/opt/swamp/sql/tools/$tool_id.sql"
+        install_sql="/opt/swamp/sql/util/tool_install.sql"
 
-for dir in $tool_scripts_dirs ; do
-    for tool_params_script in "$dir"/*.sql ; do
+        echo "Adding: $tool_id"
+        do_mysql_command "$params_sql" "$install_sql"
+    done < "/opt/swamp/etc/$inventory_file"
+done
+echo "Finished adding tools to the database"
 
-        tool=$(basename "$tool_params_script" .sql)
-        params_sql=$(cat "$tool_params_script")
-        install_sql=$(cat "$tool_install_script")
+############################################################################
 
-        echo ".. Adding: $tool"
+echo "Adding tool compatibility information to the database"
+echo "Adding: (bundled tools)"
+do_mysql_command "/opt/swamp/sql/populate_tool_metadata.sql"
 
-        if ! $mysql_command <<< "$params_sql ; $install_sql" ; then
+if ! is_mir_swamp_like_context ; then
+    for tool_meta_sql in /opt/swamp/sql/tools_add_on/*.meta.sql ; do
+        tool_id=$(basename "$tool_meta_sql" .meta.sql)
+        params_sql="/opt/swamp/sql/tools_add_on/$tool_id.sql"
 
-            echo "Error: $0: Failed to add: $tool" 1>&2
-            encountered_error=1
+        echo "select tool_version_uuid from tool_shed.tool_version where tool_uuid = @tool_uuid;" > "$sql_temp"
+        tool_version_uuids=$(do_mysql_command "$params_sql" "$sql_temp")
 
+        if [ ! -z "$tool_version_uuids" ]; then
+            while read -r tool_version_uuid ; do
+                escaped_tool_version_uuid=$tool_version_uuid
+                escaped_tool_version_uuid=${escaped_tool_version_uuid//\'/\'\'/}
+                escaped_tool_version_uuid=${escaped_tool_version_uuid//\\/\\\\/}
+
+                echo "Adding: $tool_id ($tool_version_uuid)"
+                echo "set @tool_version_uuid = '$escaped_tool_version_uuid';" > "$sql_temp"
+                do_mysql_command "$params_sql" "$sql_temp" "$tool_meta_sql"
+            done <<< "$tool_version_uuids"
         fi
     done
-done
-
-############################################################################
-
-echo "Populating metadata into the database for all tools"
-
-if ! $mysql_command < "/opt/swamp/sql/populate_tool_metadata.sql" ; then
-
-    echo "Error: $0: Failed to populate metadata into the database" 1>&2
-    encountered_error=1
-
 fi
 
-############################################################################
-
-echo "Populating additional metadata into the database for add-on tools"
-
-for tool_meta_script in "$tool_add_on_scripts_dir"/*.meta.sql ; do
-
-    tool=$(basename "$tool_meta_script" .meta.sql)
-    params_sql=$(cat "$tool_add_on_scripts_dir/$tool.sql")
-    metadata_sql=$(cat "$tool_meta_script")
-
-    tool_version_uuids=$($mysql_command -B -N <<< "$params_sql ; select tool_version_uuid from tool_shed.tool_version where tool_uuid = @tool_uuid ;")
-
-    if [ ! -z "$tool_version_uuids" ]; then
-        while read -r tool_version_uuid ; do
-            escaped_tool_version_uuid="$tool_version_uuid"
-            escaped_tool_version_uuid="${escaped_tool_version_uuid//\'/\'\'/}"
-            escaped_tool_version_uuid="${escaped_tool_version_uuid//\\/\\\\/}"
-
-            echo ".. Adding: $tool (version UUID: $tool_version_uuid)"
-
-            if ! $mysql_command <<< "$params_sql ; set @tool_version_uuid = '$escaped_tool_version_uuid' ; $metadata_sql" ; then
-
-                echo "Error: $0: Failed to add additional metadata for: $tool" 1>&2
-                encountered_error=1
-
-            fi
-        done <<< "$tool_version_uuids"
-    fi
-done
+echo "Finished adding tool compatibility information to the database"
 
 ############################################################################
 
-remove_mysql_options_file
-stop_mysql_service
+if [ $encountered_error -eq 0 ]; then
+    echo "Finished rebuilding the tools database"
+else
+    echo "Error: Finished rebuilding the tools database, but with errors" 1>&2
+fi
 
+reset_db_support
 exit $encountered_error
