1.32.194.siab_Production_Build

diff --git a/swampinabox/runtime/sbin/rebuild_tools_db b/swampinabox/runtime/sbin/rebuild_tools_db
--- a/swampinabox/runtime/sbin/rebuild_tools_db
+++ b/swampinabox/runtime/sbin/rebuild_tools_db
@@ -3,11 +3,10 @@
 # This file is subject to the terms and conditions defined in
 # 'LICENSE.txt', which is part of this source code distribution.
 #
-# Copyright 2012-2017 Software Assurance Marketplace
+# Copyright 2012-2018 Software Assurance Marketplace
 
 #
-# Rebuild the "tools" tables in the database based on the
-# tool install SQL files available on the filesystem.
+# Rebuild the "tools" tables in the database.
 #
 
 encountered_error=0
@@ -23,7 +22,7 @@ fi
 
 SWAMP_CONTEXT="$1"
 
-. /opt/swamp/sbin/db_support.functions
+source /opt/swamp/sbin/db_support.functions
 trap 'remove_mysql_options_file; stop_mysql_service; exit 1' INT TERM
 
 start_mysql_service
@@ -31,19 +30,21 @@ create_mysql_options_file
 
 ############################################################################
 
-script_to_remove_tools=""
-dirs_with_tool_scripts=""
+tool_scripts_dirs=""
+tool_add_on_scripts_dir="/opt/swamp/sql/tools_add_on"
+
 tool_install_script="/opt/swamp/sql/util/tool_install.sql"
+tool_remove_all_script=""
 
 if [ "$SWAMP_CONTEXT" = -distribution ]; then
 
-    script_to_remove_tools="/opt/swamp/sql/util/delete_non_user_tools.sql"
-    dirs_with_tool_scripts="/opt/swamp/sql/tools"
+    tool_scripts_dirs="/opt/swamp/sql/tools"
+    tool_remove_all_script="/opt/swamp/sql/util/delete_non_user_tools.sql"
 
 elif [ "$SWAMP_CONTEXT" = "-singleserver" -o "$SWAMP_CONTEXT" = "-mir-swamp" ]; then
 
-    script_to_remove_tools="/opt/swamp/sql/util/delete_all_tools.sql"
-    dirs_with_tool_scripts="/opt/swamp/sql/tools /opt/swamp/sql/tools_other"
+    tool_scripts_dirs="/opt/swamp/sql/tools /opt/swamp/sql/tools_other"
+    tool_remove_all_script="/opt/swamp/sql/util/delete_all_tools.sql"
 
 else
 
@@ -56,7 +57,7 @@ fi
 
 echo "Removing existing bundled tools from the database"
 
-if ! $mysql_command < "$script_to_remove_tools" ; then
+if ! $mysql_command < "$tool_remove_all_script" ; then
 
     echo "Error: $0: Failed to remove existing tools from the database" 1>&2
     encountered_error=1
@@ -67,18 +68,16 @@ fi
 
 echo "Adding bundled tools for the current release to the database"
 
-for dir in $dirs_with_tool_scripts; do
-    for tool_params_script in "$dir"/*.sql; do
+for dir in $tool_scripts_dirs ; do
+    for tool_params_script in "$dir"/*.sql ; do
 
-        tool="$tool_params_script"
-        tool="$(basename "$tool" .sql)"
-
-        default_params=$(cat "$tool_params_script")
-        install_script=$(cat "$tool_install_script")
+        tool=$(basename "$tool_params_script" .sql)
+        params_sql=$(cat "$tool_params_script")
+        install_sql=$(cat "$tool_install_script")
 
         echo ".. Adding: $tool"
 
-        if ! $mysql_command <<< "$default_params $install_script" ; then
+        if ! $mysql_command <<< "$params_sql ; $install_sql" ; then
 
             echo "Error: $0: Failed to add: $tool" 1>&2
             encountered_error=1
@@ -97,6 +96,38 @@ if ! $mysql_command < "/opt/swamp/sql/populate_tool_metadata.sql" ; then
     encountered_error=1
 
 fi
+
+############################################################################
+
+echo "Populating additional metadata into the database for add-on tools"
+
+for tool_meta_script in "$tool_add_on_scripts_dir"/*.meta.sql ; do
+
+    tool=$(basename "$tool_meta_script" .meta.sql)
+    params_sql=$(cat "$tool_add_on_scripts_dir/$tool.sql")
+    metadata_sql=$(cat "$tool_meta_script")
+
+    tool_version_uuids=$($mysql_command -B -N <<< "$params_sql ; select tool_version_uuid from tool_shed.tool_version where tool_uuid = @tool_uuid ;")
+
+    if [ ! -z "$tool_version_uuids" ]; then
+        while read -r tool_version_uuid ; do
+            escaped_tool_version_uuid="$tool_version_uuid"
+            escaped_tool_version_uuid="${escaped_tool_version_uuid//\'/\'\'/}"
+            escaped_tool_version_uuid="${escaped_tool_version_uuid//\\/\\\\/}"
+
+            echo ".. Adding: $tool (version UUID: $tool_version_uuid)"
+
+            if ! $mysql_command <<< "$params_sql ; set @tool_version_uuid = '$escaped_tool_version_uuid' ; $metadata_sql" ; then
+
+                echo "Error: $0: Failed to add additional metadata for: $tool" 1>&2
+                encountered_error=1
+
+            fi
+        done <<< "$tool_version_uuids"
+    fi
+done
+
+############################################################################
 
 remove_mysql_options_file
 stop_mysql_service
